### ISSUE TITLE
seven_day_accuracy help

### ISSUE THREAD

**Issue by speezlab** [NateDiR/Prop_Betting_Regression_Project#1]
Hi - great project! great article!  thank you for sharing your knowledge.

I am experimenting with the code and while I realize that BettingPros.com has likely changed it's UI since your project (so the selenium and beautifulsoup will need updates); however, I am at a loss for understanding and finding the `Accuracy` data.  It appears to be acquired from BettingPros and then parsed into `seven_day_accuracy` and cast into a float variable. 

Is this data still on BettingPros.com?  ..I couldn't tell if it's used later in the modeling and scoring?

Thanks for any help you can provide.

**Comment by VinceDiR** [comment]
Hi there, I checked the bettingpros.com URL that I originally used in this project (https://www.bettingpros.com/nba/picks/prop-bets/bet/points/) and it is indeed very different.. the UI is completely changed, and the accuracy data, which was the rolling average of correct predictions made (I think?) is no longer present. 

If I recall those fields did end up being features in the model.. I think I included a confusion matrix somewhere that can tell you their predictive power/importance to the model.

Given the changes to the UI and data available I would try to re-tool the code I've written here to work with the data that's currently available in the table-- the scraping should be largely the same, but what you get might be different. 

Also if I recall correctly a certain loop in the code will break if there are no games on a particular day so yeah, this is really brittle code lol.

**Comment by speezlab** [comment]
Thanks for the reply!   Yes, I will re-work the scraping code..  I can either remove the rolling average feature (although that would be a nice predictive power/importance) - OR I could engineer my own by taking the last 7 predictions and calculate my own rolling average for that player ....hmmm.. 

Either way, thank you for the reply and suggestions!  Cheers!
